version: '3.4'

services:
  web_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp2.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=newPassword
    ports:
      - "8000:8080"
      - "8001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${home}/.aspnet/https2:/home/app/.aspnet/https:ro