version: "3.9"  # optional since v1.27.0
services:
  web_api:
    container_name: web_api_application
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:8080"
      - "5005:8081"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
